[package]
name = "resviewer_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bincode = "1.3.3"
byteorder = "1.5.0"
eframe = "0.29.1"
egui = "0.29.1"
font-kit = "0.14.2"
image = "0.25.2"
rfd = "0.15.0"
serde = "1.0.210"
